version: "3.9"

services:
  users:
    build: ./backend/User-Service
    container_name: users-service
    ports:
      - "13001:13001"
    env_file:
      - ./backend/User-Service/.env
    networks:
      - app-network

  ads:
    build: ./backend/Ads-Service
    container_name: ads-service
    ports:
      - "13002:13002"
    env_file:
      - ./backend/Ads-Service/.env
    networks:
      - app-network
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://host.docker.internal:13002"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  billing:
    build: ./backend/Billing-Service
    container_name: billing-service
    ports:
      - "13003:13003"
    env_file:
      - ./backend/Billing-Service/.env
    networks:
      - app-network

  websocket:
    build: ./backend/websocket
    container_name: websocket
    ports:
      - "13010:8080"
    depends_on:
      ads:
        condition: service_healthy
    env_file:
      - ./backend/websocket/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  image-detector-ai:
    build: ./backend/image-detector-ai
    container_name: image-detector-ai
    ports:
      - "8009:8009"
    networks:
      - app-network

  telegram-bot:
    build: ./backend/Telegram-Bot
    container_name: telegram-bot
    env_file:
      - ./backend/Telegram-Bot/.env
    networks:
      - app-network

  kong:
    image: kong:3.9
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /config/kong.yml
    volumes:
      - ./backend/kong-gateway/kong.yml:/config/kong.yml:ro
    ports:
      - "8000:8000" # proxy (http)
      - "8443:8443" # proxy (https)
      - "8001:8001" # admin (http)
      - "8444:8444" # admin (https)
    depends_on:
      - ads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
